"""empty message

Revision ID: 15188472ef10
Revises: 947369aec0f3
Create Date: 2024-01-08 19:59:24.907411

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '15188472ef10'
down_revision = '947369aec0f3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('posts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('body', sa.String(length=130), nullable=False),
    sa.Column('time_Stamp', sa.DateTime(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('posts', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_posts_time_Stamp'), ['time_Stamp'], unique=False)
        batch_op.create_index(batch_op.f('ix_posts_user_id'), ['user_id'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('posts', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_posts_user_id'))
        batch_op.drop_index(batch_op.f('ix_posts_time_Stamp'))

    op.drop_table('posts')
    # ### end Alembic commands ###
